apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudnotes-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnotes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnotes-db
  template:
    metadata:
      labels:
        app: cloudnotes-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloudnotes-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudnotes-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cloudnotes-db-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: cloudnotes-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cloudnotes-db
spec:
  selector:
    app: cloudnotes-db
  ports:
    - port: 5432
      targetPort: 5432
